version: "3.8"

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:alpine
    networks:
      - backend
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - backend
    ports:
      - "3000:3000"
    command: >
      sh -c "
      bunx prisma db push &&
      bun run --watch src/server.ts
      "

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      SERVER_NAME: ${SERVER_NAME}
      CHOKIDAR_USEPOLLING: true
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    command: >
      sh -c "
      bun run dev:server
      "

  fileserver:
    image: nginx:alpine
    volumes:
      - ./files:/usr/share/nginx/html
    networks:
      - backend
    ports:
      - "8080:80"

networks:
  backend:
  frontend:

volumes:
  postgres-data:
